<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DataDrivenTest</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>12134187-b42c-46c7-824d-1bd054e7a654</testSuiteGuid>
   <testCaseLink>
      <guid>de4e8de8-79dd-4c4c-b49d-20fd2b5c9f3b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DataDriven</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>731c022c-c6f2-4ba5-9bc5-9aa8b8e436bc</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Driven</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>731c022c-c6f2-4ba5-9bc5-9aa8b8e436bc</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>CountryCode</value>
         <variableId>a9cfeb7a-4cf0-4ec6-baf4-6904d3877efb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>731c022c-c6f2-4ba5-9bc5-9aa8b8e436bc</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Capital</value>
         <variableId>a1f2fca5-fb0a-47dd-b701-e59e0c3866e0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>731c022c-c6f2-4ba5-9bc5-9aa8b8e436bc</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Currency1</value>
         <variableId>8fd99920-e87d-42b4-9c58-91e98e90a90d</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
